version: '3.8'

services:
  # FastAPI Application
  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-2024-08-06}
      # Optional custom base URL for OpenAI-compatible endpoints
      # - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    ports:
      - "8000:8000"
    command: >
      sh -c "
        sleep 5 &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
