"""Initial migration

Revision ID: 071540c71e08
Revises: 
Create Date: 2025-09-07 18:50:40.581497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071540c71e08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
